#!/bin/sh
types=( "feat" "fix" "docs" "style" "refactor" "perf" "test" "chore" "revert" )

min_length=3
max_length=52

msg=$(head -1 $1)
msg_length=${#msg}

if [ $msg_length -lt $min_length ]; then
  echo "Your commit message is too short. Please add a type and a description."
  exit 1
fi

if [ $msg_length -gt $max_length ]; then
  echo "Your commit message is too long. Please keep it under $max_length characters."
  exit 1
fi

for type in "${types[@]}"
do
    if [[ $msg == "$type:"* ]]; then
        exit 0
    fi
done

echo "Commit message must start with one of the following types: ${types[*]}"
exit 1